---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: "CRW"
    openshift.io/display-name: "CRW"
    argocd.argoproj.io/sync-wave: "0"
  name: openshift-workspaces
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: CheCluster.v1.org.eclipse.che
    argocd.argoproj.io/sync-wave: "1"
  name: openshift-workspaces-sbrfb
  generateName: openshift-workspaces-
  namespace: openshift-workspaces
spec:
  targetNamespaces:
  - openshift-workspaces
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: latest
  installPlanApproval: Automatic
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
